### ISSUE TITLE
Coding Review No v. N/A Issue

### ISSUE THREAD

**Issue by AJFrazer** [legalscienceio/monqcle#36]
When using the coding review tool, it appears that answer choices that are unselected are displaying as "no" instead of a blank field for certain questions. These answers are still are noted as divergences from the second series if the second series answered "no" instead of leaving it blank.  (This is a slight inconvenience, but not a major problem since they still come up as divergences). 

Here is the url where we encountered the issue: https://monqcle.com/coding_review/run/59484fa8f7d1b6c9739463a5

One example is question 3.1 where the first  coder didn't select an answer (as it was a child question) and the second coder disagreed and answered "no." 

Please let me know if there is anything else you need to address this. Thanks!

**Comment by korostelevm** [comment]
Boolean answers are stored as 0 and 1 for no and yes, so when making 'Yes' and 'No' text for display I had a rule that said - If not answer, then put 'No'. In the code nothing and 0 are equivalent. Should be fixed in the next deployment (deployments happen on 15 minute cycles). 

Also fixed the off by one day date, caution notes on the wrong side and hidden records not showing up in the coding review
