### ISSUE TITLE
Answers and citations not being saved

### ISSUE THREAD

**Issue by CateDavie** [legalscienceio/monqcle#58]
I'm working on the CRVS dataset "CRVS Enabling Environment" https://monqcle.com/dataset/crvs-enabling-environment-1504119588/code/59c012b8f5f53c2a488b456b

Question 15 and 15.1 keeps losing its answers and earlier today a few citations weren't sticking to that same question. The citations were dragged and turned green but when I would refresh the page it would appear that the citations were never dragged. I know there are a *ton* of citations but unfortunately I need to be able to add more. Thank you so much!!!

**Comment by CateDavie** [comment]
Citations and answers appear to be dropping from other questions in same datatset. Refreshing the page sometimes brings them back but not always.

**Comment by Lizzy618** [comment]
This is the last piece to finish before we can move on for CFTFK. For the time being, we have noted what we wanted coded & cited, but the client will be checking it soon.

**Comment by Lizzy618** [comment]
We tested it and found that the answers stick if you have 16 or less citations - the questions with more than 16 causes them to drop. In order to keep moving forward without coding answers dropping, we will max out at 16 citations, but we need this capacity fixed because the client likely wants all sources cited, even if its more than 16 citations.

**Comment by CateDavie** [comment]
I just tested it out and it looks like only 18 citations can be used before the answers are deleted and citations are removed from the question. Unfortunately, I need to be able to add several more citations. Thanks!
